spring.application.name=springboot

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Supabase
supabase.url=${SUPABASE_URL}
supabase.apiKey=${SUPABASE_API_KEY}
supabase.bucketName=${SUPABASE_BUCKET_NAME}

# File upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# JWT
jwt.secret=${JWT_SECRET}

# Server port Render will assign
server.port=${PORT:8080}